### ISSUE TITLE
Decrypting ProtKey not working

### ISSUE THREAD

**Issue by elichai** [WyseNynja/vanitygen#17]
elichai2@elichai-G510:~/$ ./vanitygen -1 -E 123 123
Difficulty: 1353
Estimated password crack time: >1 seconds
WARNING: Password contains only numbers
WARNING: Protecting private keys with weak password
Pattern: 123                                                                   
Address: 123zn9ZuUeXngZTC2VARHAC4FDKtPpxqoR
Protkey: PsQLg4xbPHB8m33wJckWd7SkLHtpNNRDKrcoNg5XBgCSSgR4yVUqi2v4vnQeJPtDS3hb
elichai2@elichai-G510:~/$ ./keyconv PsQLg4xbPHB8m33wJckWd7SkLHtpNNRDKrcoNg5XBgCSSgR4yVUqi2v4vnQeJPtDS3hb
keyconv: /home/elichai2/gits/vanitygen/util.c:374: vg_set_privkey: Assertion `EC_KEY_check_key(pkey)' failed.
Aborted (core dumped)

**Comment by WyseNynja** [comment]
Hmm. Its working for me. Try installing the latest version and comment if you still have the issue

**Comment by elichai** [comment]
Hey,
Thanks, but I already fixed it in my clone :)
https://github.com/elichai/vanitygen

**Comment by WyseNynja** [comment]
Want to combine our repos? I just made this fork originally so that I could get it installed with brew (https://github.com/WyseNynja/homebrew-bitcoin) but haven’t used vanitygen for a long time. I’m happy to made you a contributor for this repo or even switch the brew tap to point to your fork.

**Comment by elichai** [comment]
sure, whatever you think is better. I'm just glad to help :)

**Comment by WyseNynja** [comment]
Finally got around to adding you :) Been busy outside of GitHub.

**Comment by elichai** [comment]
Thanks, 
I'll merge my fork into yours in the next few days
